module/sheets/actor-sheet.mjs

The previous fix to init bonus worked, but it was being added to _all_ roll checks, not just initiative lol. I took a stab at seeing if I could fix it myself (kinda new-ish to coding; dabbled in the past but not enough to know much of anything). Mainly just moved some lines around to get it working right.
I've also added some tidying to the chat output for decluttering purposes; I think it looks cleaner if the "attr + attr + bonus" ignores "+ bonus" when bonus is 0. Haven't figured out where to change that for weapon/skill/spell messages, though. 
Feel free to give feedback or ignore these changes; was mainly just a self-exercise for its own sake.

Fix init bonus being added to all rolls; chat message tidying

---

module/documents/actor.mjs
module/sheets/actor-standard-sheet.mjs

Make bonds be an array. Use splice to remove a bond. Handle updates from foundry in object index->bond form by converting back into an array of bonds.
Add some conversion logic to the bond initialization code to convert previously saved object index->bond form bonds.

feat: deleting bonds removes row from sheet

---

module/fabulaultima.mjs

There is a default drag and drop handler for the macrobar.  In order to prevent the default macro from being made a hooked function needs to return false.
An async callback that awaits does not work as it returns a Promise. Instead Promise#then can be used to setup the macro creation in the background and the callback can be a non-async function that returns false when it handled the drop item.

fix: drag item onto macrobar creates roll macro

---

module/settings.js
templates/system/settings/optional-rules.hbs

- refactor settings.js
- fix optional-rules.hbs checkbox states

Fix "Manage Optional Rules" dialog

---

module/sheets/actor-standard-sheet.mjs
templates/actor/sections/actor-section-features.hbs
templates/actor/sections/actor-section-items.hbs

Details on features column fix (Ignore the changes to damage and roll):
Before: 
After:

Actor sheet fixes and tweaks

---

lang/en.json
module/helpers/checks.mjs
module/helpers/flags.mjs
module/helpers/group-check.mjs
module/helpers/templates.mjs
module/projectfu.mjs
module/sheets/actor-standard-sheet.mjs
templates/actor/partials/actor-resources.hbs
templates/app/app-group-check.hbs
templates/chat/chat-check-flavor-check.hbs
templates/chat/chat-group-check-initiated.hbs
templates/dialog/dialog-group-check.hbs

This is another experimental one, testing and feedback would be appreciated.

Add experimental group checks

---

lang/en.json
lang/it.json
module/documents/items/item.mjs
module/documents/items/weapon/weapon-data-model.mjs
module/helpers/checks.mjs
module/helpers/group-check.mjs
module/helpers/templates.mjs
module/sheets/actor-standard-sheet.mjs
templates/chat/chat-check.hbs
templates/chat/partials/chat-ability-details.hbs
templates/chat/partials/chat-basic-attack-details.hbs
templates/chat/partials/chat-check-details.hbs

- refactor checks code so that basic attacks, skills and misc abilities also use the new code
- fix old code not honoring the chat setting
- refactor old code to not require direct call of Dice So Nice
- refactor check templates

Fix chat setting being ignored

---

module/documents/items/item.mjs
module/documents/items/misc/misc-ability-data-model.mjs
module/documents/items/misc/misc-ability-migrations.mjs
module/documents/items/spell/spell-data-model.mjs
module/documents/items/spell/spell-migrations.mjs
module/helpers/templates.mjs
templates/chat/partials/chat-ability-details.hbs
templates/chat/partials/chat-item-opportunity.hbs
templates/chat/partials/chat-spell-details.hbs
templates/item/item-miscAbility-sheet.hbs
templates/item/item-spell-sheet.hbs

fixes #55
- migrate spells: quality -> opportunity
- migrate misc abilities: quality -> opportunity

Quality label on Spell instead of Opportunity

---

lang/de.json

German Translation

---

lang/de.json
lang/en.json
lang/es.json
lang/fr.json
lang/it.json
lang/pl.json
lang/pt_BR.json
module/helpers/config.mjs
module/projectfu.mjs
module/sheets/item-sheet.mjs
templates/item/item-heroic-sheet.hbs
templates/item/item-spell-sheet.hbs
templates/item/partials/item-header.hbs
templates/item/partials/item-weapon-header.hbs

Hello,
I've added the missing translations.
To do this, I had to add lines to the CONFIG file, the translation files and several template modifications.
I also corrected a problem in the display of the "Offensive" icon for spells and skills, which was repeated in the header.

Fix / Feat : Translations & Background repeating for Offensive Icons

---

module/documents/items/item.mjs
module/helpers/checks.mjs
templates/chat/partials/chat-check-details.hbs

- add support for the "autoanimations"/"Automated Animations" module by adding the item id to the check chat messages

Automated Animations Support

---

module/sheets/actor-standard-sheet.mjs
module/sheets/item-sheet.mjs
templates/actor/actor-npc-sheet.hbs
templates/item/item-accessory-sheet.hbs
templates/item/item-armor-sheet.hbs
templates/item/item-basic-sheet.hbs
templates/item/item-behavior-sheet.hbs
templates/item/item-class-sheet.hbs
templates/item/item-consumable-sheet.hbs
templates/item/item-heroic-sheet.hbs
templates/item/item-item-sheet.hbs
templates/item/item-miscAbility-sheet.hbs
templates/item/item-project-sheet.hbs
templates/item/item-ritual-sheet.hbs
templates/item/item-rule-sheet.hbs
templates/item/item-sheet.hbs
templates/item/item-shield-sheet.hbs
templates/item/item-skill-sheet.hbs
templates/item/item-spell-sheet.hbs
templates/item/item-treasure-sheet.hbs
templates/item/item-weapon-sheet.hbs
templates/item/item-zeroPower-sheet.hbs

- properly enrich foundry links in HTML fields

Description HTML Enrichment

---

module/documents/items/classFeature/class-feature-sheet.mjs
module/documents/items/classFeature/parent-document-embedded-document-field.mjs
module/helpers/checks.mjs
module/helpers/handlebars-html-enricher.mjs
module/projectfu.mjs
module/settings.js
module/sheets/actor-standard-sheet.mjs
module/ui/combat.mjs

- also remove some leftover console.log messages

Configure V11 ActiveEffect transferal

---

lang/de.json
lang/en.json
lang/es.json
lang/fr.json
lang/it.json
lang/pl.json
lang/pt_BR.json
module/documents/items/classFeature/class-feature-sheet.mjs
templates/feature/tinkerer/feature-alchemy-sheet.hbs
templates/feature/tinkerer/feature-infusions-sheet.hbs
templates/feature/tinkerer/feature-magitech-sheet.hbs
templates/item/item-class-feature-sheet.hbs
templates/item/partials/item-effects.hbs

- remove attributes tab
- make effects tab do something

Class Feature Improvements

---

module/documents/items/item.mjs
templates/actor/partials/actor-statistics.hbs
templates/actor/sections/actor-section-features.hbs

Some missing translations added.

Fix missing translations

---

module/documents/actors/actor.mjs
module/documents/actors/character/character-data-model.mjs
module/documents/actors/common/affinities-data-model.mjs
module/documents/actors/common/attributes-data-model.mjs
module/documents/actors/npc/npc-data-model.mjs
module/helpers/action-handler.mjs
module/helpers/effects.mjs
module/helpers/inline-effects.mjs
module/helpers/statuses.mjs
module/projectfu.mjs
templates/ui/combat-tracker.hbs

- make status effects work like any other active effect
- add changes to aura and barrier
- refactor status effect handling across the system to improve consistency
- fixed KO status not flagging combatants as defeated

feat: streamline status effects

---

module/checks/check-configuration.mjs
module/documents/items/spell/spell-data-model.mjs

#146 - Solving this bug I'm experiencing. Since I was opening so many I thought it only fair I try to help with them. I don't think this is ideal, it's not elegant, but there seems to be a lot of places where this logic can be injected, and a very complicated code base. If this isn't the best place to do it, then it's at least an idea of how to start? :)

fix for not using hasDamage value in checks v2

---

module/helpers/apply-damage.mjs
templates/chat/partials/chat-check-targets.hbs

👋 
I think this should solve the "Apply damage to individual targets" TODO item in your discord.

single target damage

---

module/helpers/apply-damage.mjs
module/helpers/inline-damage.mjs

Inline damage didn't have hooks applied.
Refactored the way damage application works so that there's a common entry point for any external consumers where hooks can be processed.

fix: inline damage hooks

---

module/helpers/action-handler.mjs
module/helpers/checks.mjs
module/helpers/inline-damage.mjs
module/helpers/study-roll.mjs
module/projectfu.mjs
module/sheets/actor-standard-sheet.mjs

The goal of this overhaul to study check ui easier to understand for the user.
1. User performs Study Action
2. Open Check Dialog appears
3. Applies any bonuses/modifiers
4. Study roll Dialog appears
5. Targets any tokens to study, and adjust study check total
**New features**

Feature Study Roll V2

---

module/documents/effects/effects.mjs

Fixes small issue regarding not being able to create effects!

Fix onManageActiveEffect not creating effects

---

templates/actor/partials/actor-item-name.hbs

Small fix to a template partial

fix: item template

---

module/ui/combat-hud.mjs

Changes for issue #236
Hopefully this fixes all the nonsense with my last PR.

Optimize combat hud event hooks

---

lang/en.json
module/documents/actors/actor.mjs
module/documents/items/common/progress-data-model.mjs
module/documents/items/item.mjs
module/expressions/expressions.mjs
module/helpers/inline-clocks.mjs
src/packs/skills/skill_I_ve_Heard_of_It__GkFFLkshtNlg0vgV.json
src/packs/skills/skill_Private_Stock_cjo6RghyGPUwvo1N.json
src/packs/skills/skill_Real_Treasure_lFYCdvybWS7x8e6L.json
src/packs/skills/skill_Winds_of_Trade_zXB7pBEv1JED1xkh.json

- Update inline-clocks to support PROGRESS
- Update methods to return the progress object depending on item model, to be updated soon again

Add automation for merchant entries

---

module/documents/actors/character/character-data-model.mjs
module/documents/actors/common/bonuses-data-model.mjs
module/documents/actors/npc/npc-data-model.mjs
module/pipelines/pipeline.mjs
module/pipelines/resource-pipeline.mjs

- Adds `MultipliersDataModel`, used for characters
- Implement its usage in the resource pipeline

Add multipliers model for characters

---

module/documents/effects/active-effect-config.mjs
module/documents/effects/active-effect.mjs
module/helpers/inline-effects.mjs

Add AE attribute key auto complete

---

module/checks/check-configuration.mjs
module/helpers/checks.mjs
module/helpers/player-list-enhancements.mjs
module/sheets/actor-sheet-utils.mjs
module/sheets/actor-standard-sheet.mjs

- Fixes spend meta resource invocation
- Fixes duplicate item invocation
This was caused by forgetting to update a few invocations after the refactor.

Fix spendMetaResource, duplicateItem

---

module/documents/actors/actor.mjs
module/documents/effects/active-effect.mjs
module/helpers/inline-weapon.mjs

- Implement inline weapon choice labeling, choosing the damage type
- Fix not clearing temp effects from items

Inline weapon improvements

---

src/packs/consumables/consumable_Elemental_Shard_00h8sKH3ktIFF5ei.json
src/packs/skills/skill_Arcane_Regeneration_ZTEuKRcX9erp1NDC.json

Fixed Typos in Arcane Regeneration and Elemental Shard

Fixed some compendium typos

---

src/packs/consumables/consumable_Elemental_Shard_00h8sKH3ktIFF5ei.json
src/packs/skills/skill_Arcane_Regeneration_ZTEuKRcX9erp1NDC.json

Reverts League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#325

Revert "Fixed some compendium typos"

---

module/checks/common-events.mjs
module/pipelines/study-roll.mjs
module/sheets/actor-party-sheet.mjs
module/sheets/actor-standard-sheet.mjs

Simplified the study roll handler a bit, cleared up its usage so that it works properly when GM studies NPCs themselves.

Fix study roll handler npc usage

---

module/documents/items/classFeature/chanter/verses-application.mjs

Changed the object update to updateDescription. Made key and tone optional parameters for when the value has changed. fixes #406

Fix verse dialog update procedure

---

module/ui/combat-hud.mjs
module/ui/combatant.mjs

Fix combat hud token visibility

---

module/documents/items/classFeature/invoker/invoker-integration.mjs
module/helpers/system-controls.mjs
module/helpers/targeting.mjs
module/pipelines/effects.mjs
module/settings.js
module/sheets/actor-party-sheet.mjs
module/ui/combat-hud.mjs
module/ui/metacurrency/MetaCurrencyTrackerApplication.mjs
templates/ui/combat-tracker.hbs

The APIs to defining the system controls have breaking changes which needed to be addressed.

Update the system controls setup for v13

---

module/documents/items/classFeature/invoker/game-wellspring-manager.mjs
module/helpers/system-controls.mjs
module/helpers/typedefs.mjs
module/sheets/actor-sheet.mjs
module/ui/combat-tracker.mjs
module/ui/npc-profile.mjs

- Updates the wellspring manager window to ApplicationV2

Update wellspring manager window to AppV2

---

lang/en.json
module/pipelines/damage-pipeline.mjs
module/pipelines/resource-pipeline.mjs
module/pipelines/traits.mjs

- Adds trait to ignore absorption for spells and skills. 
- Add message when damage is nullified for the damage pipeline

Add ignore absorption trait

---

module/documents/effects/active-effect-config.mjs
styles/css/global/window.css
templates/effects/active-effect-details.hbs
templates/effects/active-effect-duration.hbs
templates/effects/active-effect-predicates.hbs
templates/effects/active-effect-rules.hbs

Closes #512 
Removed the unused "details" variable. Will need to be updated as details cannot be updated as it currently stands.

Fix missing background on active effect config parts

---

module/checks/common-sections.mjs
module/documents/items/common/progress-data-model.mjs
module/documents/items/optionalFeature/quirk/quirk-data-model.mjs
module/documents/items/optionalFeature/zeropower/zeropower-data-model.mjs
module/helpers/tables/active-effects-table-renderer.mjs
templates/chat/chat-active-effect.hbs
templates/chat/chat-prompt-check.hbs
templates/chat/partials/chat-clock-details.hbs
templates/effects/active-effect-details.hbs
templates/effects/active-effect-image.hbs
templates/table/cell/cell-effect-name.hbs

- Fix description not being saved in the effect config

Fix the rendering of effects with progress in chat
