League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima

module/documents/actor.mjs
module/sheets/actor-standard-sheet.mjs

While using `Actor#_preUpdate` works to tranform the sheet/form changes, some discussion in the Foundry discord makes it sound like adapting it at the sheet/form level would be better.
This patch moves the bond conversion of `{number: bond}` to `bond[] ` into the sheet that is actually handling that form.

refactor: use `Document#_updateObject` for bond changes

---

module/documents/actor.mjs
module/fabulaultima.mjs

Updating the prototypeToken in _precreate
Removed code likely intended to do a similar thing because I couldn't find the setting `linkActorData` in settings.js

fix: character type actor prototype token linked by default

---

module/documents/actor.mjs

When I make an npc with the following:
Elemental
Immunity - Poison
Resistance - Physical, Fire
Absorbtion - Bolt
the SP tracker shows:
SP Used 3
Used skills from resistances 1
Used skills from absorption 2
However using the pdf I should be able to do it with 2 skills:
Elemental - Free Immunity - Poison, Bolt
Damage Resistance - Physical, Fire
Damage Absorbtion - Bolt
Similarly creating:
Demon
Skill 1: Resistance - Dark, Earth, Fire
Skill 2: Absorbtion - Ice
the SP tracker shows:
SP Used 2.5
Used skills from resistances 0.5
Used skills from absorption 2
However using the pdf I should be able to do it with 2 skills:
Demon - Free Resistance - Dark, Ice
Skill 1: Damage Resistance - Earth, Fire
Skill 2: Damage Absorbtion - Ice
This patch changes the skill used calculation to only count …

fix: calculate absorb skill point cost in cheapest way

---

module/documents/actors/common/damage-bonuses-data-model.mjs
module/documents/items/item.mjs
module/documents/items/shield/shield-data-model.mjs
templates/item/item-shield-sheet.hbs

- fix shield weapon category resetting
- adjust ShieldDataModel defaults to align with dual shield
- replace physical/magic damage bonuses with melee/ranged/spell
- adjust weapon and spell checks to take new bonuses for damage into account
fix #73 and #74

Offensive Shield Checks

---

lang/de.json
lang/en.json
lang/es.json
lang/fr.json
lang/it.json
lang/pl.json
lang/pt_BR.json
lang/ru.json
module/settings.js
module/ui/combat-hud.mjs

👋 
I noticed that the position of the combat hud was not staying in place, seems that _doHudDrop was never firing. I also think there **might be issues on two other draggables**, however I haven't tried to play with either of those features, so I just commented on them.
I also made it so that if the user changes between the combat hud's default position being top/bottom in the settings, the drag position is relative to that (ie if they set it to the bottom, the drag position will be relative to the bottom, not top).
In addition, I added a button to lock the position and compact/non compact mode for people (like me) who have one specific place and layout they want to keep across battles. If it's enabled, the only thing the reset combat hud button does is unminimize it. 
I needed this …

Fix _doHudDrop not firing on combat-hud, add button to save position of dragged hud on reset/combat end

---

module/documents/effects/active-effect.mjs

Looked into the bug in the support forum:
It seems target.statuses looks only at already applied statuses. Therefore anything evaluating isSuppressed relies on crisis to have been evaluated _first_ in the list, which doesn't seem to be a sure thing. (I'm not sure how the list is created, but it might be that any effect added is added in at the bottom. So crisis would always be evaluated pretty far down?)
Swapped out target.statuses for target.effects, which doesn't rely on them being evaluated in any order.
I think a problem might come up here as well if something can supress/disable crisis, target.effects is just a list of all effects the user has rather than filtering out disabled/suppressed things, but that seems far less likely than the current situation. And it would be homebrew, I …

fix isSuppressed reliant on 'crisis' being evaluated first

---

module/ui/combat-hud.mjs

👋 
I felt the HUD was pretty useless for showing effects. You don't know if any of them are disabled, or suppressed, which ones are actually effecting the actor, etc. I filtered out disabled and suppressed effects, to show only things that are actively impacting the player in the current moment.
If there's use cases where people need to see disabled/suppressed effects, it feels like you'd want to look at the character sheet, which actually shows that kind of information in detail.
@KzMz

Hide disabled/suppressed effects in the combat HUD

---

src/packs/skills/weapon_Twin_Shields_2LyT2btVVPDPYY4h.json
src/packs/skills/weapon_Twin_Shields__Runic__BronzekX5gYvdtisphOnoj.json
src/packs/skills/weapon_Twin_Shields__Runic__G7ia7CUo4fzXL4Lo.json

Hi there,
I made some tweaks to the Guardian Twin Shields ability as the book says that 'you gain the benefits of both items' (197) but in the compendium the bonus was only being applied once. I also added a Twin Shields item for when the player has one runic and one bronze shield
- Twin Shields > set def bonus to 4
- Twin Shields (Runic) > set def to 4, set magic def to 4
- Twin Shields (Runic & Bronze) > set def to 4 and magic def to 2
Sorry if I've misunderstood the conventions on how you're building items. Thanks for all your hard work, the system is looking great.

Fix: Twin Shield Tweaks

---

module/sheets/actor-standard-sheet.mjs

Hi! This should solve the issue with creating items not having the proper attributes attached.

Fix "V12 Bug, creating items in stats tab don’t autofavorite/enable click" from discord

---

templates/actor/sections/actor-section-combat.hbs

Attempt to fix issue where NPC skills and class skills/features couldn't be dragged directly from compendium to NPC sheet, since it only considered items classified as "Misc Ability". 
Added a "Skills" list to the "Combat" tab (actor-section-combat.hbs), reutilizing code from the actor-section-classes.hbs skill section.

added skill list to combat section

---

module/documents/actors/actor.mjs
module/documents/items/item.mjs
module/helpers/apply-damage.mjs
module/helpers/config.mjs
module/helpers/damage-customizer.mjs
module/helpers/inline-damage.mjs
module/helpers/study-roll.mjs
module/helpers/typedefs.mjs
module/hooks.mjs
module/projectfu.mjs

Adds two hooks to the damage pipeline.
'projectfu.damage.beforeApply' => altering overall values just before any meaningful calculations start
'projectfu.damage.applyTarget' => altering data per-target just before application
The hooks can modify the provided data structure and the changes will be picked up and propagated to the logic.
Refactors out duplicate code
Repairs and adds some JSDoc typedefs
Centralizes some hook constants for ease of lookup, enumeration, and hopefully documentation

feat: damage hooks

---

module/helpers/text-editor-command-dropdown.mjs

The text editor `@CHECK` command was not adding the bracket at the end, as it should have.

Fix text editor check command

---

module/helpers/inline-resources.mjs

The event callback function for drag-and-dropping the inline resource onto an actor had one of the parameters set incorrectly.

Fix inline resource application through dropping on an actor

---

module/expressions/expressions.mjs
module/helpers/improvised-effect.mjs
module/helpers/inline-damage.mjs
module/helpers/inline-helper.mjs
module/helpers/inline-resources.mjs

Fixes the issue where the actor's methods could not be resolved for drag events.
It came to be due to non-primitives being passed in the `.dragstart` event, which get serialized then deserialized without type information. 
I had to refactor the events and the API involved so that we only pass in the uuids for the item/actor instead then resolve it at the very end.

Fix inline source usage for events

---

src/packs/basic-equipment/armor_Silk_Shirt_23VCQdoqi2lYsVbS.json

In the core rulebook, the silk shirt gives INS die + 2 M. Defense
However in the foundry module the value is incorrectly INS die + 1 M. Defense

fix: update silk shirt mdef to correct value of 2

---

module/sheets/actor-standard-sheet.mjs

Class features are not sorted when presented on the item sheet.
Currently we only apply sorting on the entire item dataset, but not nested sub-categories like class features and optional features.

fix: item sort

---

module/checks/accuracy-check.mjs
module/checks/check-configuration.mjs
module/checks/common-events.mjs
module/checks/magic-check.mjs
module/documents/actors/actor.mjs
module/documents/items/basic/basic-item-data-model.mjs
module/documents/items/classFeature/chanter/verses-application.mjs
module/documents/items/item.mjs
module/documents/items/misc/misc-ability-data-model.mjs
module/documents/items/skill/skill-data-model.mjs
module/documents/items/spell/spell-data-model.mjs
module/documents/items/weapon/weapon-data-model.mjs
module/helpers/target-handler.mjs
module/helpers/targeting.mjs
module/hooks.mjs
module/pipelines/damage-pipeline.mjs
module/pipelines/effects.mjs
module/pipelines/resource-pipeline.mjs
module/pipelines/traits.mjs
module/ui/combat.mjs
src/packs/skills/classFeature_Calm_Tone_XCtijox9eBrBNSno.json
src/packs/skills/classFeature_Energetic_Tone_XvkMOHPXUg0ikDkf.json
src/packs/skills/classFeature_Frantic_Tone_mtKts9zjHlweSVk4.json
src/packs/skills/classFeature_Lively_Tone_zLxqETSi6zbRkWKu.json
src/packs/skills/classFeature_Solemn_Tone_yidpNKJQMA7dSBsc.json

Add a variety of combat event hooks that can be used by modules (and the system) . These can all be found in `FUHooks`.
- ATTACK_EVENT
- DAMAGE_EVENT 
- COMBAT_EVENT
- GAIN_EVENT
- LOSS_EVENT
- CRISIS_EVENT
- DEFEAT_EVENT
- STATUS_EVENT
```js
Hooks.on('projectfu.events.damage', async event => {
Azurecompendia.log(`Playing sound effect for damage event: ${event.type} on token: ${event.token.name}`);
switch (event.type) {
case "physical":
playSoundEffect('physical');
break;
default:
break;
}
});
Hooks.on('projectfu.events.gain', async event => {
Azurecompendia.log(`Playing sound effect for gain event: ${event.resource} on token: ${event.token.name}`);
});
Hooks.on('projectfu.events.loss', async event => {
Azurecompendia.log(`Playing sound effect for loss event: ${event.resource} on token: …
```

Add combat event hooks

---

module/ui/combat-hud.mjs

- fixes a bug in drag/drop where UI would jump off-screen
- fixes dragging issue with the bottom button where starting the drag would cause the top of the UI to jump to the cursor position rather than staying where the drag started
- prettier changes applied to code automatically; no logic changes after ~line 700

Fix combat hud bottom button drag

---

module/checks/common-events.mjs
module/checks/common-sections.mjs
module/documents/actors/actor.mjs
module/documents/items/consumable/consumable-data-model.mjs
module/helpers/checks.mjs
module/helpers/study-roll.mjs
module/helpers/targeting.mjs
module/hooks.mjs
module/pipelines/effects.mjs
module/sheets/actor-standard-sheet.mjs
module/ui/combat-hud.mjs
module/ui/combat-tracker.mjs
module/ui/combat.mjs
templates/ui/combat-tracker.hbs
templates/ui/partials/combat-hud-turn.hbs

- Standardizes the combat turn button across the combat hud and tracker
- Fixes taking turns out of order
- Show info for other combatants when someone's taking a turn
- Add item event

Combat turn V3

---

lang/en.json
module/helpers/inline-type.mjs
styles/static/icons/ful-sl-star.svg
styles/static/icons/fus-martial.svg

When using `@TYPE[affinity....]`, one can now do the following:
- `@TYPE[affinity all resistance]`
- `@TYPE[affinity fire,ice vulnerability]`

Add support for multiple damage types for the affinity inline

---

lang/en.json
module/documents/actors/actor.mjs
module/documents/effects/active-effect-config.mjs
module/documents/effects/active-effect-model.mjs
module/documents/effects/active-effect.mjs
module/documents/items/common/progress-data-model.mjs
module/documents/items/item.mjs
module/expressions/expressions.mjs
module/helpers/flags.mjs
module/helpers/inline-check.mjs
module/helpers/inline-clocks.mjs
module/helpers/inline-damage.mjs
module/helpers/inline-helper.mjs
module/helpers/inline-resources.mjs
module/helpers/templates.mjs
module/pipelines/damage-pipeline.mjs
module/pipelines/effects.mjs
templates/chat/chat-active-effect.hbs
templates/common/active-effects.hbs
templates/effects/active-effect-rules.hbs
templates/optional/quirk/feature-quirk-sheet.hbs

Adds progress data to the active effect model, allowing us to embed progress tracks (to serve as either clocks or resource points) into any kind of item really. This will prevent the need to inject progress-tracking into all kinds of models when they could instead become an optional part of the foundational unit that all items share, _active effects_. 
I strongly believe this approach will be more flexible going forward, and also give us and users the chance to easily introduce temporary progress tracks through temporary effects that can be easily added onto existing actors at the click of a button. The potential of this approach will give both us and our users a great deal of creative freedom.
Furthermore, by having the progress data managed within the active effect model we will be able …

Add progress data to active effect model

---

module/checks/accuracy-check.mjs
module/checks/check-configuration.mjs
module/checks/checks-v2.mjs
module/checks/magic-check.mjs
module/helpers/inline-damage.mjs
module/pipelines/damage-customizer.mjs
module/pipelines/damage-pipeline.mjs
module/pipelines/legacy-hook-data.mjs

The final calculation for initial damage has been pushed back all the way to the end, at the start of the damage pipeline. This will prevent timing issues where modifiers could be added throughout the check, then having the total modifier calculated right before yet another modifiers was then added.
This also fixes the issues when modifying checks.

Refactor damage total calculation

---

styles/css/projectfu.css
styles/scss/components/_combat.scss
styles/scss/components/_dialogs.scss
styles/scss/components/_resource.scss
styles/scss/global/_window.scss
styles/scss/utils/_colors.scss
styles/scss/utils/_icons.scss
styles/scss/utils/_typography.scss

The CSS currently uses absolute paths for styling (fonts, images, etc.) This is fine in most cases. However, in the case where something is hosted in a location with a nested path segment (imagine someone with a url of `mywebsite.com/foundry/systems/projectfu/...`) this fails, as it attemps to pull from `mywebsite.com/systems/projectfu/...` path instead, which is invalid.
Anywhere that points to the absolute path `/systems/projectfu/styles` should be replaced with `..`. This PR is a simple find and replace to do just that. There is already precedence for this in the CSS, as the RPGAwesome import uses this format.

Replaces absolute paths with relative paths

---

lang/en.json
module/checks/check-configuration.mjs
module/checks/magic-check.mjs
module/documents/items/spell/spell-data-model.mjs
module/documents/items/weapon/weapon-data-model.mjs
module/pipelines/damage-pipeline.mjs
module/pipelines/traits.mjs

- Adds a trait, `MindPointAbsorption` to specify that MP should be regained on absorption.
- Fixes spellblade not accounting for weapon accuracy

Add mind point absorption trait, Fix spellblade weapon accuracy

---

module/checks/accuracy-check.mjs
module/checks/check-configuration.mjs
module/checks/magic-check.mjs

When updating the procedure for target results on accuracy check, the same was not done for magic check. That has now been addressed.

Fix updating target results on magic check
